import serviceImg1 from "./serviceImages/service-1.png";
import serviceImg2 from "./serviceImages/service-2.png";
import serviceImg3 from "./serviceImages/service-3.png";
import serviceImg4 from "./serviceImages/service-4.png";
import blogImg1 from "./blogImages/blog-img1.png";
import blogImg2 from "./blogImages/blog-img2.png";
import blogImg3 from "./blogImages/blog-img3.png";
import sliderImg1 from "./sliderImages/slide-img-1.png";
import sliderImg2 from "./sliderImages/slide-img-2.png";
import sliderImg3 from "./sliderImages/slide-img-3.png";
import sliderImg4 from "./sliderImages/slide-img-4.png";
import flightLogo from "./images/airline-logo.png";
import stayImg1 from "./stayImages/staysImg1.png";
import stayImg2 from "./stayImages/staysImg2.png";
import stayImg3 from "./stayImages/staysImg3.png";
import stayImg4 from "./stayImages/staysImg4.png";

export const serviceData = [
  {
    id: 1,
    heading: "Book Flight",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg1,
  },
  {
    id: 2,
    heading: "Book Hotels",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg2,
  },
  {
    flightLogo,
    heading: "Book Cruises",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg3,
  },
  {
    id: 4,
    heading: "Book family Vacation",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg4,
  },
];

export const blogData = [
  {
    id: 1,
    body: "Interesting Tibetan Traditions",
    imgSrc: blogImg1,
  },
  {
    id: 2,
    body: "Are There Volcanos In Hawaii?",
    imgSrc: blogImg2,
  },
  {
    id: 3,
    body: "Winter in Iceland",
    imgSrc: blogImg3,
  },
  {
    id: 4,
    body: "Interesting Tibetan Traditions",
    imgSrc: blogImg1,
  },
  {
    id: 5,
    body: "Are There Volcanos In Hawaii?",
    imgSrc: blogImg2,
  },
  {
    id: 6,
    body: "Winter in Iceland",
    imgSrc: blogImg3,
  },
];

export const modalServiceData = [
  {
    id: 1,
    heading: "Book Flight",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg1,
  },
  {
    id: 2,
    heading: "Book Hotels",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg2,
  },
  {
    id: 3,
    heading: "Book Cruises",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg3,
  },
  {
    id: 4,
    heading: "Book family Vacation",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg4,
  },
  {
    id: 5,
    heading: "Book Flight",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg1,
  },
  {
    id: 6,
    heading: "Book Hotels",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg2,
  },
  {
    id: 7,
    heading: "Book Cruises",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg3,
  },
  {
    id: 8,
    heading: "Book family Vacation",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg4,
  },
  {
    id: 9,
    heading: "Book Flight",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg1,
  },
  {
    id: 10,
    heading: "Book Hotels",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg2,
  },
  {
    id: 11,
    heading: "Book Cruises",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg3,
  },
  {
    id: 12,
    heading: "Book family Vacation",
    body: "book memorable journey with our flight booking services! we're thrilled to present you flight options to suit your travel needs.",
    imgSrc: serviceImg4,
  },
];

export const sliderData = [
  {
    id: 1,
    imgSrc: sliderImg1,
    city: "Barcelona",
    country: "Spain",
    adultCount: 2,
    days: 7,
    price: 2400,
  },
  {
    id: 2,
    imgSrc: sliderImg2,
    city: "Rome",
    country: "Italy",
    adultCount: 2,
    days: 3,
    price: 1800,
  },
  {
    id: 3,
    imgSrc: sliderImg3,
    city: "Paris",
    country: "France",
    adultCount: 2,
    days: 4,
    price: 2100,
  },
  {
    id: 4,
    imgSrc: sliderImg4,
    city: "Luxor City",
    country: "Egypt",
    adultCount: 2,
    days: 3,
    price: 800,
  },
  {
    id: 5,
    imgSrc: sliderImg1,
    city: "Barcelona",
    country: "Spain",
    adultCount: 2,
    days: 7,
    price: 2400,
  },
  {
    id: 6,
    imgSrc: sliderImg2,
    city: "Rome",
    country: "Italy",
    adultCount: 2,
    days: 3,
    price: 1800,
  },
  {
    id: 7,
    imgSrc: sliderImg3,
    city: "Paris",
    country: "France",
    adultCount: 2,
    days: 4,
    price: 2100,
  },
  {
    id: 8,
    imgSrc: sliderImg4,
    city: "Luxor City",
    country: "Egypt",
    adultCount: 2,
    days: 3,
    price: 800,
  },
  {
    id: 9,
    imgSrc: sliderImg1,
    city: "Barcelona",
    country: "Spain",
    adultCount: 2,
    days: 7,
    price: 2400,
  },
  {
    id: 10,
    imgSrc: sliderImg2,
    city: "Rome",
    country: "Italy",
    adultCount: 2,
    days: 3,
    price: 1800,
  },
  {
    id: 11,
    imgSrc: sliderImg3,
    city: "Paris",
    country: "France",
    adultCount: 2,
    days: 4,
    price: 2100,
  },
  {
    id: 12,
    imgSrc: sliderImg4,
    city: "Luxor City",
    country: "Egypt",
    adultCount: 2,
    days: 3,
    price: 800,
  },
];

export const flightsData = [
  {
    id: 1,
    takeoffTime: 8,
    landingTime: 10,
    duration: 2,
    stop: "direct",
    isDirect: true,
    isOneStop: false,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 3000,
  },
  {
    id: 2,
    takeoffTime: 9,
    landingTime: 12,
    duration: 3,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 1500,
  },
  {
    id: 3,
    takeoffTime: 11,
    landingTime: 14,
    duration: 3,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 2000,
  },
  {
    id: 4,
    takeoffTime: 13,
    landingTime: 16,
    duration: 3,
    stop: "direct",
    isDirect: true,
    isOneStop: false,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 800,
  },
  {
    id: 5,
    takeoffTime: 15,
    landingTime: 18,
    duration: 3,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 400,
  },
  {
    id: 6,
    takeoffTime: 17,
    landingTime: 20,
    duration: 3,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 200,
  },
  {
    id: 7,
    takeoffTime: 19,
    landingTime: 22,
    duration: 3,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 300,
  },
  {
    id: 8,
    takeoffTime: 21,
    landingTime: 24,
    duration: 3,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 600,
  },
  {
    id: 9,
    takeoffTime: 10,
    landingTime: 12,
    duration: 2,
    stop: "twoStop",
    isDirect: false,
    isOneStop: false,
    isTwoStop: true,
    imgSrc: flightLogo,
    price: 900,
  },
  {
    id: 10,
    takeoffTime: 11,
    landingTime: 13,
    duration: 2,
    stop: "twoStop",
    isDirect: false,
    isOneStop: false,
    isTwoStop: true,
    imgSrc: flightLogo,
    price: 1100,
  },
  {
    id: 11,
    takeoffTime: 12,
    landingTime: 14,
    duration: 2,
    stop: "direct",
    isDirect: true,
    isOneStop: false,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 600,
  },
  {
    id: 12,
    takeoffTime: 13,
    landingTime: 15,
    duration: 2,
    stop: "twoStop",
    isDirect: false,
    isOneStop: false,
    isTwoStop: true,
    imgSrc: flightLogo,
    price: 1300,
  },
  {
    id: 13,
    takeoffTime: 14,
    landingTime: 16,
    duration: 2,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 100,
  },
  {
    id: 14,
    takeoffTime: 15,
    landingTime: 17,
    duration: 2,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 800,
  },
  {
    id: 15,
    takeoffTime: 16,
    landingTime: 18,
    duration: 2,
    stop: "direct",
    isDirect: true,
    isOneStop: false,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 1000,
  },
  {
    id: 16,
    takeoffTime: 17,
    landingTime: 19,
    duration: 2,
    stop: "twoStop",
    isDirect: false,
    isOneStop: false,
    isTwoStop: true,
    imgSrc: flightLogo,
    price: 900,
  },
  {
    id: 17,
    takeoffTime: 18,
    landingTime: 20,
    duration: 2,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 500,
  },
  {
    id: 18,
    takeoffTime: 19,
    landingTime: 21,
    duration: 2,
    stop: "twoStop",
    isDirect: false,
    isOneStop: false,
    isTwoStop: true,
    imgSrc: flightLogo,
    price: 600,
  },
  {
    id: 19,
    takeoffTime: 20,
    landingTime: 22,
    duration: 2,
    stop: "oneStop",
    isDirect: false,
    isOneStop: true,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 300,
  },
  {
    id: 20,
    takeoffTime: 21,
    landingTime: 23,
    duration: 2,
    stop: "direct",
    isDirect: true,
    isOneStop: false,
    isTwoStop: false,
    imgSrc: flightLogo,
    price: 400,
  },
];

export const staysData = [
  {
    id: 1,
    img: stayImg1,
    text: "Hotels",
  },
  {
    id: 2,
    img: stayImg2,
    text: "Apartments",
  },
  {
    id: 3,
    img: stayImg3,
    text: "Resorts",
  },
  {
    id: 4,
    img: stayImg4,
    text: "Villas",
  },

  {
    id: 5,
    img: stayImg1,
    text: "Hotels",
  },
  {
    id: 6,
    img: stayImg2,
    text: "Apartments",
  },
  {
    id: 7,
    img: stayImg3,
    text: "Resorts",
  },
  {
    id: 8,
    img: stayImg4,
    text: "Villas",
  },

  {
    id: 9,
    img: stayImg1,
    text: "Hotels",
  },
  {
    id: 10,
    img: stayImg2,
    text: "Apartments",
  },
  {
    id: 11,
    img: stayImg3,
    text: "Resorts",
  },
  {
    id: 12,
    img: stayImg4,
    text: "Villas",
  },
];
